version: 2.1

jobs:
  config_cisco:
    machine: true
    resource_class: harutoendo/cisco-resouce

    steps:
      - run:
          name: Debug Variables
          command: |
            echo "USER=$CISCO_USER"
            echo "PASS_LENGTH=${#CISCO_PASS}"
            echo "HOST=$CISCO_HOST"

workflows:
  config:
    jobs:
      - config_cisco